### ISSUE TITLE
Pull Requests - priority list Q4

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1002]
Priority list for `whosonfirst-data` PRs, Q4.

**High priority:**
_Top list items more important than bottom items._

- [x] #824 -⏳⏳ QS point gazetteer import + names + populations
- [x] #980 -⏳ Updates to dependency records
- [x] #1024 - ⏳ Fix St Petersburg, Russia

**Lower priority:**
_Top list items more important than bottom items._

- [ ] #700 - ⏳ New and updated county features for Austria
- [x] #804 - 🎈 Updated neighbourhood records with dual hierarchies
- [x] #780 - ⏳ Quebec City/Levis neighbourhood import
- [x] #421 - ⏳ Vancouver (and surrounding) neighbourhood imports
- [x] #984 - 🎈Untangled duplicate Tirana records duplicate
- [x] #946 - 🎈Updates to the Tokelau and NZ empire updates
- [ ] #839 - 🎈Updated St Martin records
- [ ] #764 - ⏳ Slovenia admin updates and new features
- [ ] #697 - ⏳ Updated geometries for Austrian region records, new alt-geoms 
- [ ] #684 - 🎈Updates to Diego Garcia NB record and new region
- [ ] #657 - 🎈Canary Islands record updates
- [ ] #656 - 🎈Region and country record updates in Tuvalu
- [x] #619 - 🎈Merged two Sweden region records of Jämtland
- [ ] #778 - 🎈Updates to admin areas in the US
- [ ] #1017 - 🎈Reversegeo polygon for Nigeria
- [ ] #1028 - 🎈Updates to Australia and France
- [ ] #1052 -  📋 New shortcodes and label abbreviations for regions in six countries
- [ ] #1015 - 🎈Reworked neighbourhoods in Alexandria

**Neighbourhoods:**
- [x] #411 -⏳ Neighbourhood updates for London
- [x] #413 - ⏳ Neighbourhood updates for Madrid
- [x] #415 - ⏳ Neighbourhood updates for Barcelona
- [x] #837 -⏳ Neighbourhood updates for the Netherlands
- [x] #413 - ⏳ Madrid neighbourhood import

### Legend 

- 📋 property edits only
- 🎈 easy sailing (not many features)
- ⏳ moderate number of features
- ⏳⏳ large number of features
- 📝 PIP in progress (by Aaron)
- 📥 PIP in review (with Stephen)
