### ISSUE TITLE
Update neighbourhood records for markets that have not yet been imported

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#680]
For the markets listed below, we need to make sure that the following work is done before importing into Who's On First:

- All neighbourhood features that fall within or near the new locality boundary are clipped at the new boundary and given `reversegeo` properties that fall outside of the new locality.
- All admin features within a locality are given `reversegeo` properties.
- All admin features within a locality are given `controlled` properties if their `parent_id` value is `-3`.
- Updating erroneous and empty string values in various properties.
_________________

**Completed markets:**

- [x] ~~San Francisco~~ - #316 
- [x] ~~Seattle~~ - #381 
- [x] ~~Chicago~~ - #385 
- [x] ~~New York~~ - #384 
- [x] ~~Los Angeles~~ - #387 
- [x] ~~Philadelphia~~ - #386 
- [x] ~~Berlin~~ https://github.com/whosonfirst-data/whosonfirst-data/issues/161
- [x] ~~Boston / Cambridge / Somerville~~ - #389 
- [x] ~~Washington DC / Arlington / Alexandria~~ - #388 
- [x] ~~Minneapolis / St Paul~~ - #390 
- [x] ~~Rotterdam/The Hague/Utrecht~~ https://github.com/whosonfirst-data/whosonfirst-data/issues/633
- [x] ~~Amsterdam~~ https://github.com/whosonfirst-data/whosonfirst-data/issues/625
- [x] ~~Greater Finland~~ - #568 

**Completed markets that need a second pass:**
- [x] ~~New Orleans~~ via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [x] ~~Baltimore~~ via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [x] ~~San Jose~~ via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [x] ~~Portland~~ via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [x] ~~San Diego~~ via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [x] ~~Denver~~ via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [x] ~~Atlanta~~ via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [x] ~~Oakland~~ via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [x] ~~Helsinki~~ via https://github.com/whosonfirst-data/whosonfirst-data/issues/659

**Comment by nvkelso** [comment]
And which of those have been fully imported into WOF (alphabetical):

- [ ] Amsterdam https://github.com/whosonfirst-data/whosonfirst-data/issues/625
- [x] Atlanta via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [x] Baltimore via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [x] Berlin https://github.com/whosonfirst-data/whosonfirst-data/issues/161
- [x] Boston / Cambridge / Somerville - #389 
- [ ] Chicago - #385 
- [x] Denver via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [ ] Greater Finland - #568 
- [x] Helsinki via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [x] Los Angeles - #387 
- [ ] Minneapolis / St Paul - #390 
- [x] New Orleans via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [ ] New York - #384 IN PROGRESS
- [x] Oakland via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [x] Philadelphia - #386 
- [x] Portland via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [ ] Rotterdam/The Hague/Utrecht https://github.com/whosonfirst-data/whosonfirst-data/issues/633
- [x] San Diego via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [ ] San Francisco - #316 (on @stepps00)
- [ ] San Jose via https://github.com/whosonfirst-data/whosonfirst-data/issues/659
- [ ] Seattle - #381 
- [ ] Washington DC / Arlington / Alexandria - #388
