### ISSUE TITLE
Pull Requests - priority list June 2017

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#833]
Priority list for `whosonfirst-data` PRs. 

**High priority:**
(mesoshapes imports and cleanups, preventing Statoids import)

_Top list items more important than bottom items._

- [x] 🎈[https://github.com/whosonfirst/whosonfirst-data/issues/622](
https://github.com/whosonfirst/whosonfirst-data/issues/622) (Sudan and S Sudan, 2 features)
- [x] 🎈[https://github.com/whosonfirst/whosonfirst-data/issues/614](https://github.com/whosonfirst/whosonfirst-data/issues/614) (New Zealand, Chile, China, Pakistan/India, Azerbaijan, Laos, Serbia, 118 features)
- [x] 🎈📝 [https://github.com/whosonfirst/whosonfirst-data/issues/626](https://github.com/whosonfirst/whosonfirst-data/issues/626) (Thailand, 135 features)
- [x] 🎈[https://github.com/whosonfirst/whosonfirst-data/issues/569](https://github.com/whosonfirst/whosonfirst-data/issues/569) (Indonesia, 140 features)
- [x] 🎈[https://github.com/whosonfirst/whosonfirst-data/issues/652](https://github.com/whosonfirst/whosonfirst-data/issues/652) (Ukraine, 257 features)
- [x] 🎈[https://github.com/whosonfirst/whosonfirst-data/issues/642](https://github.com/whosonfirst/whosonfirst-data/issues/642)  (Kosovo and Serbia, 410 features)
- [x] ⏳📥 [https://github.com/whosonfirst/whosonfirst-data/issues/561](https://github.com/whosonfirst/whosonfirst-data/issues/561) (Armenia, Guinea, Malawi, Morocco, Zimbabwe, Ivory Coast, Namibia, Equatorial Guinea, Kazakhstan, 1700 features)
- [x] ⏳⏳📥 [https://github.com/whosonfirst/whosonfirst-data/issues/660](https://github.com/whosonfirst/whosonfirst-data/issues/660) (admin1, 4600 features, global)
- [x] ⏳[https://github.com/whosonfirst/whosonfirst-data/issues/566](https://github.com/whosonfirst/whosonfirst-data/issues/566) (Japan, 3000 features)

**Lower priority:**

- [x] 🎈Duplicate Bratislava (Slovakia) localities, 6 features #609
- [x] 🎈Add province names in Belgium, 6 features #653
- [x] 🎈Add localadmin in Belgium, 309 features  #679
- [x] 🎈📥Overseas insular regions of France, 171 features https://github.com/whosonfirst-data/whosonfirst-data/pull/832
- [x] 🎈Add postalcodes in Belgium, 26 features https://github.com/whosonfirst-data/whosonfirst-data-postalcode-be/pull/1
- [x] ⏳⏳📝 [https://github.com/whosonfirst-data/whosonfirst-data/issues/705](https://github.com/whosonfirst-data/whosonfirst-data/issues/705) (oversized US zetashape rural neighbourhoods, 10,000+ features, most of the USA)

**Completed prior to mid-June:**

- [x] Neighbourhoods curation, mix of PRs and S3 work #680
- [x] Mesoshapes county (adm2) polygons
    - [x] #555
    - [x] #559
    - [x] #620
- [x] Mesoshape country polygons #686
- [x] Austria localadmin #698
- [x] New French 2016 regions #655
- [x] Duplicate New Zealand localities #654 

### Legend 

- 📋 property edits only
- 🎈 easy sailing (not many features)
- ⏳ moderate number of features
- ⏳⏳ large number of features
- 📝 PIP in progress (by Aaron)
- 📥 PIP in review (with Stephen)

**Comment by thisisaaronland** [comment]
* 660 is running over the weekend on a dedicated machine and will do whatever it feels like
* 566 is running over the weekend
* 626 has merge conflicts
* 561 will be attended to post 660/566
* everything else is on @stepps00 's desk

**Comment by thisisaaronland** [comment]
* 566 and 561 are now on @stepps00 's desk

**Comment by thisisaaronland** [comment]
* 609 is now on @stepps00 's desk

**Comment by thisisaaronland** [comment]
* 679 is now on @stepps00 's desk

**Comment by thisisaaronland** [comment]
* 832 is now on @stepps00 's desk

**Comment by thisisaaronland** [comment]
* 705 has merge conflicts – https://github.com/whosonfirst-data/whosonfirst-data/pull/705#issuecomment-313916455

**Comment by thisisaaronland** [comment]
* 660 is now on @stepps00 's desk

**Comment by thisisaaronland** [comment]
* 705 is processing... I expect it will take a while since... America is big
* everything else has been merged in to master

**Comment by thisisaaronland** [comment]
* 705 is sitting on @stepps00 's desk
* 660 is being re-processed after I noticed some problems with the last merge

**Comment by thisisaaronland** [comment]
* https://github.com/whosonfirst-data/whosonfirst-data/compare/pr-660-3 is sitting on @stepps00 's desk again

**Comment by stepps00** [comment]
@nvkelso - all PRs have been taken care of, I'm working on a priority list v2 right now. Suggest we close this issue and link the new priority list shortly.

**Comment by nvkelso** [comment]
Next priority list is https://github.com/whosonfirst-data/whosonfirst-data/issues/864.
